# =============================================
# CONFIG
# =============================================

# Templates
templates:         site/templates
layouts:           <%= site.templates %>/layouts
layout:            default
pages:             <%= site.templates %>/pages
includes:          <%= site.templates %>/{includes, pages}


# =============================================
# METADATA
# =============================================

# Site
title:              Gray Ghost Visuals
url:                http://grayghostvisuals.com