# =============================================
# CONFIG
# =============================================

# site
root:             .
dest:             <%= site.root %>
data:             data

# assemble
templates:         site/templates
layouts:           <%= site.templates %>/layouts
layout:            default
pages:             <%= site.templates %>/pages
includes:          <%= site.templates %>/{includes,pages}

# assets
imgdir:            ./img/site/
js:                ./js/src/
jslib:             ./js/lib/
bowerlib:          ./bower_components/


# =============================================
# META
# =============================================

# site
title:              Gray Ghost Visuals
author:             Dennis Gaebel
url:                http://grayghostvisuals.com