# =============================================
# CONFIG
# =============================================

# site
root:             .
dest:             <%= site.root %>
data:             data

# assemble
templates:         site/templates
layouts:           <%= site.templates %>/layouts
layout:            default
pages:             <%= site.templates %>/pages
includes:          <%= site.templates %>/{includes,pages}

# assets
css:               <%= site.root %>/css/
imgdir:            <%= site.root %>/img/site/
js:                <%= site.root %>/js/src/
jslib:             <%= site.root %>/js/lib/
bower:             <%= site.root %>/bower_components/


# =============================================
# META
# =============================================

# site
title:              Gray Ghost Visuals
author:             Dennis Gaebel
email:              grayghost@grayghostvisuals.com
url:                http://grayghostvisuals.com
tel:                5859449406