# =============================================
# CONFIG
# =============================================

root:             .
dest:             <%= site.root %>
data:             data

# Templates
templates:         site/templates
layouts:           <%= site.templates %>/layouts
layout:            default
pages:             <%= site.templates %>/pages
includes:          <%= site.templates %>/{includes, pages}


# =============================================
# META
# =============================================

# Site
title:              Gray Ghost Visuals
author:             <%= pkg.author %>
url:                <%= pkg.homepage %>